<gardenplan>
  <plan title="my plan" gridSize="11.1111111" gridWidth="1500" gridHeight="1500" version="3.0"/>
  <objects>
    <item obType="tool" id="-1" x="358" y="42.65" width="517.6" height="4" rotation="0" title="wall" description="" currentFillColour="0" depth="0" depthType="3" currentFlowerColour="" locked="false" inReport="true" plantType="houseFixtures" toolMode="line" toolNum="2" numTools="1" shapeType="-1" toolStyle="1" distBetweenObjects="0" toolArrayX="-310.85,200.85" toolArrayY="0.65,0.65" curveArrayX="" curveArrayY=""/>
    <item obType="tool" id="-1" x="358" y="268.65" width="515.6" height="4" rotation="0" title="wall" description="" currentFillColour="0" depth="1" depthType="3" currentFlowerColour="" locked="false" inReport="true" plantType="houseFixtures" toolMode="line" toolNum="2" numTools="1" shapeType="-1" toolStyle="1" distBetweenObjects="0" toolArrayX="-310.85,198.85" toolArrayY="0.65,0.65" curveArrayX="" curveArrayY=""/>
    <item obType="tool" id="-1" x="560" y="181.3" width="4" height="229.9" rotation="0" title="wall" description="" currentFillColour="0" depth="2" depthType="3" currentFlowerColour="" locked="false" inReport="true" plantType="houseFixtures" toolMode="line" toolNum="2" numTools="1" shapeType="-1" toolStyle="1" distBetweenObjects="0" toolArrayX="0,0" toolArrayY="-136.85,88.2" curveArrayX="" curveArrayY=""/>
    <item obType="object" id="9" x="302" y="156.65" width="512" height="220.9" rotation="0" title="square" description="" currentFillColour="15122307" depth="3" depthType="3" currentFlowerColour="" locked="false" inReport="true"/>
    <item obType="object" id="9" x="348" y="190.65" width="416" height="43.8" rotation="0" title="square" description="" currentFillColour="39321" depth="4" depthType="3" currentFlowerColour="" locked="false" inReport="true"/>
    <item obType="tool" id="-1" x="46" y="181.3" width="4" height="227.85" rotation="0" title="wall" description="" currentFillColour="0" depth="5" depthType="3" currentFlowerColour="" locked="false" inReport="true" plantType="houseFixtures" toolMode="line" toolNum="2" numTools="1" shapeType="-1" toolStyle="1" distBetweenObjects="0" toolArrayX="0,0" toolArrayY="-136.85,86.2" curveArrayX="" curveArrayY=""/>
    <item obType="object" id="207" x="58" y="116.65" width="50" height="30" rotation="90" title="door%0A%20style%20%232" description="" currentFillColour="16777215" depth="0" depthType="4" currentFlowerColour="" locked="false" inReport="true"/>
    <item obType="tool" id="-1" x="100" y="100" width="270.7" height="4" rotation="0" title="wall" description="" currentFillColour="0" depth="6" depthType="3" currentFlowerColour="" locked="false" inReport="true" plantType="houseFixtures" toolMode="line" toolNum="2" numTools="1" shapeType="-1" toolStyle="1" distBetweenObjects="0" toolArrayX="-132.85,132.85" toolArrayY="0,0" curveArrayX="" curveArrayY=""/>
    <item obType="object" id="183" x="310" y="60.65" width="29.6" height="27.6" rotation="0" title="oval%20table" description="" currentFillColour="6697779" depth="7" depthType="3" currentFlowerColour="" locked="false" inReport="true"/>
    <item obType="object" id="173" x="540" y="56.65" width="30" height="18" rotation="0" title="chili" description="" currentFillColour="0" depth="0" depthType="0" currentFlowerColour="" locked="false" inReport="true"/>
  </objects>
  <notes/>
</gardenplan>